# Generated by Django 4.0.3 on 2022-03-20 21:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('priority', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('category_cover', models.ImageField(default='app_brandon_photography/img/photos/IMG_3266.JPG/', upload_to='app_brandon_photography/img/photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_site_visibility', models.BooleanField()),
                ('category_cover', models.BooleanField()),
                ('priority', models.IntegerField(default=99, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('photo', models.ImageField(upload_to='app_brandon_photography/img/photos/')),
                ('photo_tumb', models.ImageField(editable=False, upload_to='app_brandon_photography/img/thumbs/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_brandon_photography.photocategory')),
            ],
        ),
    ]
