# Generated by Django 4.0.3 on 2025-04-24 19:07

import app_brandon_photography.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('green', 'Available'), ('yellow', 'Partially Booked'), ('red', 'Unavailable')], default='green', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='app_brandon_photography/img/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(default='Nagy Ádám', max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('extract', models.CharField(max_length=200)),
                ('content', django_quill.fields.QuillField()),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('priority', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('category_cover', models.ImageField(default='app_brandon_photography/img/photos/IMG_3266.JPG/', upload_to='app_brandon_photography/img/photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stars', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('owner', models.TextField(default='', max_length=200)),
                ('photo', models.ImageField(default='app_brandon_photography/img/photos/default.jpg', upload_to='app_brandon_photography/img/photos/')),
                ('photo_tumb', models.ImageField(default='app_brandon_photography/img/photos/default.jpg', editable=False, upload_to='app_brandon_photography/img/thumbs/')),
            ],
            bases=(app_brandon_photography.models.ImageHandlerMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='app_brandon_photography/img/photos/')),
                ('photo_tumb', models.ImageField(editable=False, upload_to='app_brandon_photography/img/thumbs/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_brandon_photography.photocategory')),
            ],
        ),
    ]
