# Generated by Django 4.0.3 on 2023-01-22 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_brandon_photography', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='category_cover',
        ),
        migrations.AlterField(
            model_name='photos',
            name='priority',
            field=models.IntegerField(default=99, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
