# Generated by Django 4.0.3 on 2025-04-24 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_brandon_photography', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Blogposzt', 'verbose_name_plural': 'Blogposztok'},
        ),
        migrations.AlterModelOptions(
            name='photocategory',
            options={'verbose_name': 'Fotó Kategória', 'verbose_name_plural': 'Fotó Kategóriák'},
        ),
    ]
