# Generated by Django 4.0.3 on 2025-04-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_brandon_photography', '0002_alter_blogpost_options_alter_photocategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name': 'Elérhetőség', 'verbose_name_plural': 'Elérhetőségek'},
        ),
        migrations.AlterModelOptions(
            name='photos',
            options={'verbose_name': 'Fotó', 'verbose_name_plural': 'Fotók'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Vélemény', 'verbose_name_plural': 'Vélemények'},
        ),
        migrations.RemoveField(
            model_name='photocategory',
            name='category_cover',
        ),
        migrations.RemoveField(
            model_name='photocategory',
            name='priority',
        ),
    ]
