# Generated by Django 4.0.3 on 2023-03-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_brandon_photography', '0002_alter_photos_priority'),
        ('app_brandon_photography', '0002_remove_photos_category_cover_alter_photos_priority'),
    ]

    operations = [
    ]
