# Generated by Django 4.0.3 on 2025-04-25 14:53

import app_brandon_photography.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_brandon_photography', '0003_alter_availability_options_alter_photos_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='app_brandon_photography/img/photos/')),
                ('photo_tumb', models.ImageField(editable=False, upload_to='app_brandon_photography/img/thumbs/')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('duration', models.CharField(max_length=100)),
                ('edited_photos', models.IntegerField()),
                ('extra_photo_price', models.TextField()),
                ('extra_info', models.TextField()),
                ('terms_pdf', models.FileField(blank=True, null=True, upload_to='terms_pdfs/')),
            ],
            options={
                'verbose_name': 'Csomag',
                'verbose_name_plural': 'Csomagok',
            },
            bases=(app_brandon_photography.models.ImageHandlerMixin, models.Model),
        ),
    ]
