# Generated by Django 4.0.3 on 2023-04-08 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_brandon_photography', '0003_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='extract',
            field=models.CharField(default='2022', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='main_image',
            field=models.ImageField(default='valami', upload_to='app_brandon_photography/img/photos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='user',
            field=models.CharField(default='valami', max_length=200),
            preserve_default=False,
        ),
    ]
