# Generated by Django 4.0.3 on 2023-04-09 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_brandon_photography', '0003_merge_20230323_1600'),
        ('app_brandon_photography', '0005_blogpost_title_alter_blogpost_user'),
    ]

    operations = [
    ]
