# Generated by Django 4.0.3 on 2024-11-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_brandon_photography', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='photo',
            field=models.ImageField(default='app_brandon_photography/img/photos/default.jpg', upload_to='app_brandon_photography/img/photos/'),
        ),
        migrations.AddField(
            model_name='review',
            name='photo_tumb',
            field=models.ImageField(default='app_brandon_photography/img/photos/default.jpg', editable=False, upload_to='app_brandon_photography/img/thumbs/'),
        ),
    ]
