# Generated by Django 4.0.3 on 2024-11-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_brandon_photography', '0006_merge_20230409_1034'),
        ('app_brandon_photography', '0006_review'),
    ]

    operations = [
    ]
