# Generated by Django 4.0.3 on 2024-11-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_brandon_photography', '0007_review_photo_review_photo_tumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='owner',
            field=models.TextField(default='', max_length=200),
        ),
    ]
