# Generated by Django 4.0.3 on 2024-12-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_brandon_photography', '0008_review_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('green', 'Available'), ('yellow', 'Partially Booked'), ('red', 'Unavailable')], default='green', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
