# Generated by Django 4.0.3 on 2024-11-26 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_brandon_photography', '0007_merge_0006_merge_20230409_1034_0006_review'),
        ('app_brandon_photography', '0008_review_owner'),
    ]

    operations = [
    ]
