# Generated by Django 4.0.3 on 2024-12-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_brandon_photography', '0009_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='bla-bla', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
