# Generated by Django 4.0.3 on 2024-12-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_brandon_photography', '0009_availability'),
        ('app_brandon_photography', '0009_merge_20241126_2037'),
    ]

    operations = [
    ]
