# Generated by Django 4.0.3 on 2025-04-23 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_brandon_photography', '0011_alter_blogpost_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='main_site_visibility',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='priority',
        ),
    ]
