# Generated by Django 4.0.3 on 2025-04-23 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_brandon_photography', '0010_merge_0009_availability_0009_merge_20241126_2037'),
        ('app_brandon_photography', '0012_remove_photos_main_site_visibility_and_more'),
    ]

    operations = [
    ]
