# Generated by Django 4.0.3 on 2025-04-23 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_brandon_photography', '0013_merge_20250423_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='priority',
        ),
    ]
