# Generated by Django 4.0.3 on 2022-03-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_brandon_photography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photocategory',
            name='category_cover',
            field=models.ImageField(default='app_brandon_photography/img/photos/category-cover.jpg', upload_to='app_brandon_photography/img/photos/'),
        ),
    ]
