# Generated by Django 4.0.3 on 2022-03-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_brandon_photography', '0003_alter_photocategory_category_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocategory',
            name='category_cover',
            field=models.ImageField(default='app_brandon_photography/img/photos/DJI_0930-HDR-Pano.jpg/', upload_to='app_brandon_photography/img/photos/'),
        ),
    ]
