# Generated by Django 4.0.3 on 2022-03-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_brandon_photography', '0004_alter_photocategory_category_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocategory',
            name='category_cover',
            field=models.ImageField(default='app_brandon_photography/img/photos/IMG_3266.JPG/', upload_to='app_brandon_photography/img/photos/'),
        ),
    ]
